rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-2.0
  - jruby
  - ree
gemfile:
  - gemfiles/Gemfile.rails3_0
  - gemfiles/Gemfile.rails3_1
env:
  - JRUBY_OPTS="--server"
script: "bundle exec rake travis"
before_script:
  - "sh -c 'cd spec/dummy && rake db:migrate RAILS_ENV=test'"
  - "sh -e /etc/init.d/xvfb start"
